export default HydrantExifUploadStats = {
    ADDED: "ADDED",
    ALREADY_EXIST_WITH_IMAGE: "ALREADY_EXIST_WITH_IMAGE",
    NO_EXIF_DATA: "NO_EXIF_DATA",
    DUPLICATE: "DUPLICATE",
    UPDATED_IMAGE: "UPDATED_IMAGE"
}